### ISSUE TITLE
Dimscord (v1.6.0) todolist

### ISSUE THREAD

**Issue by krisppurg** [krisppurg/dimscord#108]
## todo:
 - [x] Update new fields to objects esp with new endpoints and stuff
 - [ ] ~~#109~~ (to be continued...)
 - [x] New event handler features e.g. `{.once(discord).}`, waitForEvent(), etc.
  (see: #106)
- [ ] ~~jsony -> jsonutils~~ (to be continued...)
- [x] [etf support](https://github.com/metagn/etf)
- [x] #118

Will update the list and will release

**Comment by ire4ever1190** [comment]
What would `etf` support look like?

**Comment by krisppurg** [comment]
It's pretty much a replacement of the encoding of json. Instead of sending json you send an etf packet instead and is I think iirc is faster. There are other discord libraries that support this like eris, nostrum, discordgo, etc

**Comment by krisppurg** [comment]
read more here at:
https://discord.com/developers/docs/topics/gateway#using-etf-encoding

**Comment by ire4ever1190** [comment]
Oh neat, didn't know it supported that
