### ISSUE TITLE
Dimscord (v1.8.0) TODO List

### ISSUE THREAD

**Issue by krisppurg** [krisppurg/dimscord#124]
currently in draft form. will make edits.

## TODO
- [x] update typedefs.nim with newer objects and update fields
- [x] new restapi methods
- [ ] ~~perhaps remove etf??? because it's slower than json~~ (LEFT FOR LATER)
- [x] clarification and some adjustments with docs
- [x] maybe have a look at previous versions and see whats hasnt been added yet.

**Comment by krisppurg** [comment]
Just an update here, Dimscord v1.8.0 will be released in this september. Sorry for any delays caused.

**Comment by krisppurg** [comment]
new todo in process
currently in draft form. will make edits.

## TODO
- [] message components v2 support
- [] merge #133 
- [] new rest api, endpoints and objects
- [] ask treeform to fix up jsonys lame error messages

**Comment by krisppurg** [comment]
v1.8.0 is going to be released
